import { Router } from "express";
import { adminInvitationSchema, normalizeNigerianPhone, verificationDecisionSchema } from "@leetlogic/contracts";
import { prisma } from "@leetlogic/database";
import { requireAuth, requirePermission, requireRecentStepUp } from "../middleware/auth.js";
import { AppError } from "../lib/errors.js";
import { audit } from "../services/audit.js";
import { LocalPrivateObjectStorage } from "../services/storage.js";

export const adminRouter = Router(); adminRouter.use(requireAuth("admin"));
adminRouter.post("/invitations", requirePermission("admin.manage"), requireRecentStepUp, async (req, res) => { const body = adminInvitationSchema.parse(req.body); const phone = normalizeNigerianPhone(body.phone); const role = await prisma.adminRole.findUnique({ where: { code: body.roleCode } }); if (!role) throw new AppError(422, "ROLE_NOT_FOUND", "Role does not exist"); const admin = await prisma.adminAccount.create({ data: { phoneE164: phone, fullName: body.fullName, invitedById: req.auth!.sub, roles: { create: { roleId: role.id } } } }); await audit(req, { action: "admin.invited", entityType: "admin_account", entityId: admin.id, after: { phone, roleCode: body.roleCode } }); res.status(201).json({ admin }); });
adminRouter.get("/verifications", requirePermission("verification.read"), async (req, res) => { const cases = await prisma.verificationCase.findMany({ where: { status: { in: ["SUBMITTED", "UNDER_REVIEW", "RESUBMISSION_REQUIRED"] } }, orderBy: { submittedAt: "asc" }, include: { farmerProfile: { include: { user: { include: { profile: true } } } }, _count: { select: { documents: true, evidence: true } } } }); res.json({ cases }); });
adminRouter.get("/verifications/:id", requirePermission("verification.read"), async (req, res) => { const caseId = String(req.params.id); const item = await prisma.verificationCase.findUnique({ where: { id: caseId }, include: { farmerProfile: { include: { user: { include: { profile: true } }, primaryAddress: true } }, documents: true, evidence: true, reviews: true } }); if (!item) throw new AppError(404, "VERIFICATION_NOT_FOUND", "Verification case was not found"); const storage = new LocalPrivateObjectStorage(); const documents = await Promise.all(item.documents.map(async document => ({ ...document, encryptedObjectKey: undefined, readUrl: await storage.createReadUrl(document.id, 300) }))); await audit(req, { action: "verification.sensitive_viewed", entityType: "verification_case", entityId: item.id }); res.json({ verification: { ...item, documents } }); });
async function decide(req: any, res: any, decision: "APPROVED" | "REJECTED") { const body = verificationDecisionSchema.parse(req.body); const caseId = String(req.params.id); const item = await prisma.verificationCase.findUnique({ where: { id: caseId } }); if (!item || !["SUBMITTED", "UNDER_REVIEW"].includes(item.status)) throw new AppError(409, "VERIFICATION_NOT_REVIEWABLE", "Verification cannot be decided"); const status = decision; await prisma.$transaction([prisma.verificationReview.create({ data: { verificationCaseId: item.id, reviewerAdminId: req.auth.sub, decision, reason: body.reason, internalNotes: body.internalNotes } }), prisma.verificationCase.update({ where: { id: item.id }, data: { status, decidedAt: new Date() } }), prisma.farmerProfile.update({ where: { id: item.farmerProfileId }, data: { verificationStatus: status } })]); await audit(req, { action: `verification.${decision.toLowerCase()}`, entityType: "verification_case", entityId: item.id, after: { status, reason: body.reason } }); res.json({ id: item.id, status }); }
adminRouter.post("/verifications/:id/approve", requirePermission("verification.decide"), async (req, res) => decide(req, res, "APPROVED"));
adminRouter.post("/verifications/:id/reject", requirePermission("verification.decide"), async (req, res) => decide(req, res, "REJECTED"));
adminRouter.get("/audit-logs", requirePermission("audit.read"), async (req, res) => { const logs = await prisma.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 100 }); res.json({ logs: logs.map(x => ({ ...x, id: x.id.toString() })) }); });
