import { Router } from "express";
import { farmEvidenceSchema, submitVerificationSchema, verificationDocumentSchema } from "@leetlogic/contracts";
import { prisma } from "@leetlogic/database";
import { requireAuth } from "../middleware/auth.js";
import { AppError } from "../lib/errors.js";
import { encryptSecret } from "../lib/crypto.js";

export const verificationRouter = Router(); verificationRouter.use(requireAuth("customer"));
async function currentCase(userId: string) { const farmer = await prisma.farmerProfile.findUnique({ where: { userId } }); if (!farmer) throw new AppError(404, "SELLER_PROFILE_REQUIRED", "Create a seller profile first"); const item = await prisma.verificationCase.findFirst({ where: { farmerProfileId: farmer.id }, orderBy: { createdAt: "desc" }, include: { documents: true, evidence: true, reviews: true } }); if (!item) throw new AppError(404, "VERIFICATION_NOT_FOUND", "Verification case was not found"); return { farmer, item }; }
verificationRouter.get("/", async (req, res) => { const { farmer, item } = await currentCase(req.auth!.sub); res.json({ farmer, verification: item }); });
verificationRouter.post("/", async (req, res) => { const { farmer, item } = await currentCase(req.auth!.sub); if (!["DRAFT", "RESUBMISSION_REQUIRED"].includes(item.status)) throw new AppError(409, "VERIFICATION_LOCKED", "Verification is already under review"); res.json({ farmer, verification: item }); });
verificationRouter.post("/documents", async (req, res) => { const body = verificationDocumentSchema.parse(req.body); const { item } = await currentCase(req.auth!.sub); if (!["DRAFT", "RESUBMISSION_REQUIRED"].includes(item.status)) throw new AppError(409, "VERIFICATION_LOCKED", "Documents cannot be changed now"); const document = await prisma.verificationDocument.create({ data: { verificationCaseId: item.id, documentType: body.documentType, encryptedObjectKey: encryptSecret(body.objectKey), mimeType: body.mimeType, checksumSha256: body.checksumSha256, referenceLastFour: body.referenceLastFour } }); res.status(201).json({ document: { ...document, encryptedObjectKey: undefined } }); });
verificationRouter.post("/evidence", async (req, res) => { const body = farmEvidenceSchema.parse(req.body); const { item } = await currentCase(req.auth!.sub); if (!["DRAFT", "RESUBMISSION_REQUIRED"].includes(item.status)) throw new AppError(409, "VERIFICATION_LOCKED", "Evidence cannot be changed now"); const evidence = await prisma.farmEvidence.create({ data: { verificationCaseId: item.id, encryptedObjectKey: body.objectKey ? encryptSecret(body.objectKey) : undefined, note: body.note } }); res.status(201).json({ evidence: { ...evidence, encryptedObjectKey: undefined } }); });
verificationRouter.post("/submit", async (req, res) => { submitVerificationSchema.parse(req.body); const { farmer, item } = await currentCase(req.auth!.sub); if (!item.documents.length) throw new AppError(422, "IDENTITY_DOCUMENT_REQUIRED", "At least one identity document is required"); const verification = await prisma.verificationCase.update({ where: { id: item.id }, data: { status: "SUBMITTED", submittedAt: new Date() } }); await prisma.farmerProfile.update({ where: { id: farmer.id }, data: { verificationStatus: "SUBMITTED" } }); res.json({ verification }); });
