export const openapi = {
  openapi: "3.1.0", info: { title: "Leetlogic API", version: "0.1.0", description: "Phase One identity, verification and administration API" },
  servers: [{ url: "/v1" }],
  components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } }, schemas: { Error: { type: "object", properties: { error: { type: "object", required: ["code", "message", "requestId"], properties: { code: { type: "string" }, message: { type: "string" }, fieldErrors: { type: "object" }, requestId: { type: "string", format: "uuid" }, retryAfterSeconds: { type: "integer" } } } } } } },
  paths: {
    "/auth/otp/request": { post: { summary: "Request customer OTP", responses: { "202": { description: "Accepted" }, "422": { description: "Invalid request" } } } },
    "/auth/otp/verify": { post: { summary: "Verify customer OTP", responses: { "200": { description: "Authenticated" } } } },
    "/auth/refresh": { post: { summary: "Rotate customer refresh token", responses: { "200": { description: "Rotated" } } } },
    "/auth/logout": { post: { summary: "Log out this customer device", security: [{ bearerAuth: [] }], responses: { "204": { description: "Logged out" } } } },
    "/auth/logout-all": { post: { summary: "Log out every customer device", security: [{ bearerAuth: [] }], responses: { "204": { description: "Logged out" } } } },
    "/me": { get: { summary: "Current customer", security: [{ bearerAuth: [] }], responses: { "200": { description: "Current user" } } }, patch: { summary: "Update customer profile", security: [{ bearerAuth: [] }], responses: { "200": { description: "Updated" } } } },
    "/me/locale": { patch: { summary: "Change preferred locale", security: [{ bearerAuth: [] }], responses: { "200": { description: "Updated" } } } },
    "/me/seller-profile": { post: { summary: "Activate seller capability", security: [{ bearerAuth: [] }], responses: { "201": { description: "Created" } } } },
    "/seller/verification": { get: { summary: "Current farmer verification", security: [{ bearerAuth: [] }], responses: { "200": { description: "Verification" } } } },
    "/seller/verification/documents": { post: { summary: "Add identity document metadata", security: [{ bearerAuth: [] }], responses: { "201": { description: "Created" } } } },
    "/seller/verification/evidence": { post: { summary: "Add farm or business evidence", security: [{ bearerAuth: [] }], responses: { "201": { description: "Created" } } } },
    "/seller/verification/submit": { post: { summary: "Submit verification", security: [{ bearerAuth: [] }], responses: { "200": { description: "Submitted" } } } },
    "/admin/auth/otp/request": { post: { summary: "Request administrator OTP", responses: { "202": { description: "Accepted" } } } },
    "/admin/auth/otp/verify": { post: { summary: "Verify administrator OTP", responses: { "200": { description: "Pre-authenticated" } } } },
    "/admin/auth/totp/enrol": { post: { summary: "Enroll an authenticator", responses: { "200": { description: "Enrollment created" } } } },
    "/admin/auth/totp/confirm": { post: { summary: "Confirm TOTP and log in", responses: { "200": { description: "Authenticated" } } } },
    "/admin/auth/totp/step-up": { post: { summary: "Confirm TOTP for a sensitive action", security: [{ bearerAuth: [] }], responses: { "200": { description: "Confirmed" } } } },
    "/admin/auth/refresh": { post: { summary: "Rotate administrator refresh token", responses: { "200": { description: "Rotated" } } } },
    "/admin/auth/logout": { post: { summary: "Log out administrator device", security: [{ bearerAuth: [] }], responses: { "204": { description: "Logged out" } } } },
    "/admin/invitations": { post: { summary: "Invite an administrator", security: [{ bearerAuth: [] }], responses: { "201": { description: "Invited" } } } },
    "/admin/verifications": { get: { summary: "Verification review queue", security: [{ bearerAuth: [] }], responses: { "200": { description: "Review queue" } } } },
    "/admin/verifications/{id}": { get: { summary: "Read a verification case", security: [{ bearerAuth: [] }], responses: { "200": { description: "Verification case" } } } },
    "/admin/verifications/{id}/approve": { post: { summary: "Approve verification", security: [{ bearerAuth: [] }], responses: { "200": { description: "Approved" } } } },
    "/admin/verifications/{id}/reject": { post: { summary: "Reject verification", security: [{ bearerAuth: [] }], responses: { "200": { description: "Rejected" } } } },
    "/admin/audit-logs": { get: { summary: "Read audit records", security: [{ bearerAuth: [] }], responses: { "200": { description: "Audit records" } } } },
  },
} as const;
